name: imgify
description: A mobile app for image processing - convert, resize, and compress images

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP client
  dio: ^5.3.3

  # Image picker
  image_picker: ^1.0.4

  # File system
  path_provider: ^2.1.1

  #Share
  share_plus:

  # Permissions
  permission_handler: ^11.0.1
  http: ^1.6.0
  path: ^1.9.1
  gallery_saver_plus: ^3.2.9
  device_preview: ^1.3.1

  #Firebase
  firebase_core:
  firebase_analytics:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons:

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/logo.png
